-- 1. Tambah kolom ke table users untuk menampung username, google_id, auth_provider, dan approval_status
ALTER TABLE public.users
ADD COLUMN username character varying(50) UNIQUE,
ADD COLUMN google_id character varying(255) UNIQUE,
ADD COLUMN auth_provider character varying(20) DEFAULT 'credentials' NOT NULL,
ADD COLUMN approval_status character varying(30) DEFAULT 'pending_otp' NOT NULL;

-- Ubah default is_active menjadi false untuk user baru karena harus di-approve dahulu
ALTER TABLE public.users ALTER COLUMN is_active SET DEFAULT false;

-- Kolom password_hash dibuat NULLABLE karena user Google login tidak memiliki password lokal
ALTER TABLE public.users ALTER COLUMN password_hash DROP NOT NULL;

-- 2. Buat tabel untuk menampung kode OTP dummy
CREATE TABLE public.user_otps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES public.users(id) ON DELETE CASCADE,
    otp_code character varying(6) NOT NULL,
    expired_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
